[features]
seeds = false
skip-lint = false
[programs.localnet]
encode_capstone_project = "2fEUszgesnJpufDjX3VzGzN8h1CMeAPyj1J6staE5hoZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
